### PR TITLE
Small Changes

### PR DESCRIPTION
**Pull request by InfoBlock**
Fixed your GitHub Button link and added another Button

### CODE REVIEW

**Comment by ymdwa** [comment]
Thank you once again for doin this stuff. 
Would you mind posting the new website link to my thread on the Hypixel forums? I accidentally unlinked my account and now I can't post for like 5 days lol.

**Comment by InfoBlock** [comment]
Should be able to do that

**Comment by InfoBlock** [comment]
Sent the new link to both of your threads

**Comment by InfoBlock** [comment]
IMG_1486
IMG_1487

**Pull request merged**
